[package]
name = "fm-control"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
fm-auth = { path = "../fm-auth" }
fm-automation = { path = "../../features/fm-automation" }
fm-clock = { path = "../../media/fm-clock" }
fm-command = { path = "../../foundation/fm-command" }
fm-engine = { path = "../fm-engine" }
fm-protocol = { path = "../../foundation/fm-protocol" }
fm-switcher = { path = "../../features/fm-switcher" }

[dev-dependencies]
fm-types = { path = "../../foundation/fm-types" }

[lints]
workspace = true
