[package]
name = "fm-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
fm-auth = { path = "../fm-auth" }
fm-control = { path = "../fm-control" }
fm-protocol = { path = "../../foundation/fm-protocol" }

[lints]
workspace = true
