[package]
name = "fm-io-network"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
fm-codec-api = { path = "../fm-codec-api" }
fm-frame = { path = "../../media/fm-frame" }
fm-io-api = { path = "../fm-io-api" }

[lints]
workspace = true
